### ISSUE TITLE
[Feature request] Linear regression functions

### ISSUE THREAD

**Issue by jamesrswift** [Sett17/typst-statastic#1]
Hi there,

I'm hoping you might consider adding regression functions (linear, quadratic, exponential, higher order polynomial) to this package

**Comment by dikkadev** [comment]
Hi, it's unlikely that I'd do that in the near future. But I'd be happy to review/help with a PR

**Comment by dikkadev** [comment]
There now are regression functions included in commit d525748d4a3877fffde27562d8a10b5652c17e43
and they will be in version 1.0.0 when that is merged https://github.com/typst/packages/pull/1158
